### ISSUE TITLE
When a user signs up, we want them to receive an email.

### ISSUE THREAD

**Issue by jeremydanner** [schiedel-sweden/API#10]
When a user signs up, we want them to receive an email confirming that they created an account

**Comment by alihossein** [comment]
There is so many email Verification with larval tutorials. Why do not you use them?
https://hackernoon.com/how-to-use-queue-in-laravel-5-4-for-email-verification-3617527a7dbf
or
http://bensmith.io/email-verification-with-laravel

**Comment by jeremydanner** [comment]
This is a feature we want to add but do not have the time ATM. Thought if someone wanted to help us it can saved us a lot of time. @alihossein

**Comment by ghost** [comment]
I would like to work on this!
